### ISSUE TITLE
Napalm get_environment() issues with IOSXR

### ISSUE THREAD

**Issue by hgandhi7760** [jvanderaa/ansible_netbox_demo#2]
Ran into the below issue while executing napalm get_environment() on IOSXR (ASR9K) Cisco network gear: -
**raise XMLCLIError(error_msg, self)
pyIOSXR.exceptions.XMLCLIError:
Original call was: <?xml version="1.0" encoding="UTF-8"?><Request MajorVersion="1" MinorVersion="0"><Get><AdminOperational><MemorySummary>            </MemorySummary></AdminOperational></Get></Request>**

########
Code is pretty easy
driver = napalm.get_network_driver('iosxr')
password = getpass('password: ')
ssh_config_file = '/Users/.ssh/config_bkp'
spoke_device = driver(hostname=spoke_router, username=username, password=password,
                          optional_args={'ssh_config_file': ssh_config_file})
spoke_device.open()
device_heath = spoke_device.get_environment()
spoke_device.close()
pp(device_heath)
#######

However, Napalm get_environment() Works perfectly fine with Junos and IOSXE. Can someone please help. Thanks!

**Comment by jvanderaa** [comment]
Does it work with NAPALM outside of NetBox? It is likely a NAPALM thing over that of a Netbox. The NTC slack has channels dedicated to both NAPALM and NetBox that may be of more assistance. Otherwise the NAPALM repo https://github.com/napalm-automation/napalm or NetBox mailing group would be of better connection methods.
